"""
ai_detection.py — Module 4: AI-Generated Content Detection
============================================================
Provides functionality to detect whether a given text is generated by AI
or written by a human.

It uses a Logistic Regression classifier trained on TF-IDF features. 
In a production setting, this would be trained on a large dataset (e.g.,
Ghostbuster, HC3) and loaded from disk. For this module, we simulate
the training with a robust dummy dataset on initialization.
"""

import logging
from typing import Dict, Any
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

logger = logging.getLogger(__name__)

# Single instance of the trained model
_AI_MODEL_PIPELINE = None

def _train_dummy_model() -> Pipeline:
    """
    Trains a Logistic Regression model on a simulated dataset of Human vs. AI text.
    In real production, this would load a pre-trained .pkl file.
    """
    logger.info("Training AI Detection Model...")
    
    # Dummy dataset (0 = Human, 1 = AI)
    # AI text often has less variance (perplexity) and distinct vocabulary patterns.
    # Human text often has more colloquialisms, varied sentence structures.
    texts = [
        "In conclusion, it is important to note that the implications are vast.", # AI-like
        "Furthermore, the multifaceted nature of this paradigm shift cannot be understated.", # AI-like
        "As an AI language model, I don't have personal opinions, but...", # AI-like
        "The results demonstrate a significant correlation between the variables.", # AI-like
        "To summarize, this essay has explored the various aspects of the topic.", # AI-like
        
        "I really think this whole thing is kind of a mess to be honest.", # Human-like
        "So we ran the tests and the data was pretty weird.", # Human-like
        "This paper tries to figure out why people do what they do.", # Human-like
        "I'm not entirely sure if the method worked, but we got some numbers.", # Human-like
        "My dog ate the homework so I had to rewrite it fast.", # Human-like
    ]
    labels = [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
    
    pipeline = Pipeline([
        ('tfidf', TfidfVectorizer(ngram_range=(1, 2))),
        ('clf', LogisticRegression(random_state=42, class_weight='balanced'))
    ])
    
    pipeline.fit(texts, labels)
    logger.info("AI Detection Model trained successfully.")
    return pipeline

def get_ai_detector() -> Pipeline:
    """Returns the trained AI detection model, initializing it if necessary."""
    global _AI_MODEL_PIPELINE
    if _AI_MODEL_PIPELINE is None:
        _AI_MODEL_PIPELINE = _train_dummy_model()
    return _AI_MODEL_PIPELINE

def detect_ai_content(text: str) -> Dict[str, float]:
    """
    Predicts the probability that the given text is AI-generated.
    
    Returns:
    {
        "ai_probability": float,
        "human_probability": float
    }
    """
    if not text or not text.strip():
        return {"ai_probability": 0.0, "human_probability": 0.0}
        
    model = get_ai_detector()
    
    try:
        # Predict probabilities
        probs = model.predict_proba([text])[0]
        # Class 0 is Human, Class 1 is AI
        human_prob = probs[0]
        ai_prob = probs[1]
        
        return {
            "ai_probability": round(ai_prob * 100, 2),
            "human_probability": round(human_prob * 100, 2)
        }
    except Exception as exc:
        logger.error(f"Error during AI detection: {exc}")
        return {"ai_probability": 0.0, "human_probability": 0.0}
